# https://moznion.hatenadiary.com/entry/2017/12/17/224043
version: "3.9"

services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.21.0
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
    volumes:
      - dynamodb:/data
    ports:
      - "4566:8000"

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-1
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb

volumes:
  dynamodb:
