# https://moznion.hatenadiary.com/entry/2017/12/17/224043
version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rust
      MYSQL_PASSWORD: rust
      MYSQL_DATABASE: rust
      TZ: "Asia/Tokyo"
    volumes:
      - mysql:/data/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql_mode="STRICT_TRANS_TABLES"

  mysql-admin:
    container_name: mysql-admin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    depends_on:
      - mysql
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    # https://docs.localstack.cloud/references/configuration/
    environment:
      - DEBUG=1
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodb-admin:
    container_name: localstack-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=localstack:4566
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-1
    ports:
      - "8001:8001"
    depends_on:
      - localstack

volumes:
  mysql:
