name: test

on:
  push:

jobs:
  test-read-model-updater:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test
        - run: |
            ls -la
            pwd
