name: test

on:
  push:

jobs:
  test-read-model-updater:
    name: Build & test
    strategy:
      rust:
        - stable
        - 1.66.1

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          profile: minimal

      - name: Build & test
        env:
          RUST_VERSION: ${{ matrix.rust }}
        run: ls -la
